sudo: false
language: nix

cache:
  directories:
  - $HOME/.stack
  - ./.stack-work

before_install:

install:
- travis_wait nix-env -i stack cabal2nix
- cabal2nix --shell . > shell.nix
- travis_wait stack --nix --no-terminal --skip-ghc-check setup

script:
- travis_wait stack --nix --no-terminal haddock
