sudo: false
language: nix

cache:
  directories:
  - $HOME/.stack
  - ./.stack-work

install:
- travis_wait nix-env -i stack cabal2nix
- cabal2nix --shell . > shell.nix
- stack --nix --no-terminal --skip-ghc-check setup

script:
- stack --nix --no-terminal haddock
- git clone https://$GIT_USER:$GIT_PASS@github.com/jano017/Discord.hs.git -b docs _site/
- cp $(stack path --local-doc-root --nix)/discord-*/* docs/build
- stack exec --nix docs build
- cd _site && git push
