sudo: false
language: nix
cache:
  directories:
  - "$HOME/.stack"
  - "./.stack-work"
install:
- nix-channel --update
- travis_wait nix-env -i stack cabal2nix
- cabal2nix --shell . > shell.nix
- stack --nix --no-terminal --skip-ghc-check setup
script:
- stack --nix --no-terminal build
- '[[ -n "$TRAVIS_TAG" ]] && echo -e "$HACKAGE_USER\n$HACKAGE_PASS" | stack upload --no-signature . || echo "Tag not set"'
