resolver: lts-8.0

flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
    - time-locale-compat-0.1.1.3
resolver: lts-8.0
nix:
  shell-file: shell.nix

