name: CI

# when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:

  # Allows manually starting this workflow from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate GHC build matrix
    runs-on: ubuntu-latest
    outputs:
      ghc-matrix: ${{ steps.set-ghc-matrix.outputs.versions }}
    steps:
      - id: set-ghc-matrix
        run: echo "::set-output name=versions::{\"ghc-version\":[\"8.10.7\", \"9.2\", \"9.4\"]}"

  build:
    name: Build Check
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.ghc-matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v2
        with:
          # The system GHC version
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
          stack-setup-ghc: true
      - name: Cache .stack
        id: cache-stack
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
          restore-keys: |
              ${{ runner.os }}-stack
              ${{ runner.os }}
      - run: stack build
